### ISSUE TITLE
simulate function seed parameter

### ISSUE THREAD

**Issue by frozenranger** [maximtrp/mchmm#1]
Dear Maximtrp,

Thank you for this great offering! I am really finding good use for your module. I have noticed some strange behavior with the seed parameter in your simulate function. When I set the seed= 100 or 1000 or 10**9 or anything at all (``a.simulate(500, start='a', seed=100)``), I get lots of repetition between states for example: ``['a','a','a','a','a','a'.....]``

However when the parameter is not included at all (``a.simulate(500, start='h')``), I get better behavior: ``['h' 'l' 'h' 'h' 'l' 'd' 'a' 'e' 'e' 'a' 'e' 'e' 'b' 'g' 'h' 'h' 'h' 'i' 'b' 'h' 'i' 'g' 'l' 'i' 'd']``, the states switch to other states and I get something much more useful instead of a string of the same character. 

Just letting you know... 

Thanks again for some great code :)

**Comment by maximtrp** [comment]
Hello! Thank you for reporting! I will look into this problem

**Comment by maximtrp** [comment]
@frozenranger 
I am afraid it may even be a bad idea to specify any seed at all. I need some more time to explore this issue.

**Comment by frozenranger** [comment]
Np! Thank you for the hard work. I really enjoy your module. I believe it is the only one that actually allows the simulation of a string of text. I was wondering if it would be possible to specify short strings instead of single characters when creating the markov chain from data? for example instead of "AAAAAABBBBBBCCCCCCC" could it be "AA, BB, CC, AB, BC, CA" or "AAA, BBB, CCC, ABC" etc?

**Comment by maximtrp** [comment]
@frozenranger 
Yes, you can specify a list of any labels as an input sequence:

```python
seq = ["AA", "BB", "CC", "AB", "BC", "CA"]
a = mc.MarkovChain().from_data(seq)
```
Though, I have discovered that NaNs are not replaced with zeros in transition probability matrix. It will be fixed in the next version.

---
I have introduced a workaround for the bug you described here. Now, you should provide a list of random seeds (its length is equal to the number of states you are going to simulate). It helps the algorithm not to fall into a deadlock loop:

```python
ids, states = a.simulate(10, start='A', seed=np.random.randint(0, 10, 10))
```
